# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "gcdm"
version = "0.1.0"
dependencies = [
 "goreecloud-download-core",
]

[[package]]
name = "goreecloud-download-core"
version = "0.1.0"
