[package]
name = "goreecloud-download-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
goreecloud-download-state = { path = "../download-state" }

[dev-dependencies]
goreecloud-download-core = { path = "../download-core" }

[lints]
workspace = true
